"use client";

import { FormEvent, useEffect, useState } from "react";
import { authedFetch, isAuthenticated } from "@/lib/auth";
import { useRouter } from "next/navigation";

type Center = { kpis: { students: number; faculty: number; departments: number; attendance: number; pendingAssignments: number }; recommendedActions: string[]; atRiskStudents: { student: { firstName: string; lastName: string }; risk: string; scores: { academicHealth: number }; recommendations: string[] }[] };
type AskAnswer = { answer: string; evidence: unknown; actions: string[] };
const questions = ["Which students require immediate academic intervention?", "Which departments need attention this month?", "Which department has the largest attendance decline?", "What are the biggest placement skill gaps?"];

export default function IntelligencePage() {
  const router = useRouter(); const [center, setCenter] = useState<Center | null>(null); const [question, setQuestion] = useState(questions[0]); const [answer, setAnswer] = useState<AskAnswer | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!isAuthenticated()) { router.replace("/login"); return; } authedFetch<{ data: Center }>("/intelligence/command-center").then(x => setCenter(x.data)).catch(e => setError(e.message)); }, [router]);
  async function ask(e: FormEvent) { e.preventDefault(); setError(""); try { const r = await authedFetch<{ data: AskAnswer }>("/ask-acadlyx", { method: "POST", body: JSON.stringify({ question }) }); setAnswer(r.data); } catch (e) { setError(e instanceof Error ? e.message : "Unable to answer"); } }
  if (error && !center) return <main className="p-8 text-sm text-red-600">{error}</main>;
  const metrics = center ? [["Students", center.kpis.students], ["Faculty", center.kpis.faculty], ["Departments", center.kpis.departments], ["Attendance", `${center.kpis.attendance}%`], ["Overdue work", center.kpis.pendingAssignments]] : [];
  return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold tracking-widest text-acadlyx-secondary">ACADLYX — INSTITUTIONAL COMMAND CENTER</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">Academic, operational and career intelligence</h1><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{metrics.map(([label, value]) => <div className="rounded-xl border border-slate-200 bg-white p-4" key={String(label)}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold text-slate-900">{value}</p></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Students requiring intervention</h2><div className="mt-3 space-y-3">{center?.atRiskStudents.length ? center.atRiskStudents.map(s => <div className="flex items-start justify-between border-b border-slate-100 pb-3 text-sm" key={`${s.student.firstName}${s.student.lastName}`}><div><p className="font-medium">{s.student.firstName} {s.student.lastName}</p><p className="text-slate-500">{s.recommendations[0] || "Faculty review required"}</p></div><span className="font-semibold text-red-600">{s.risk} · {s.scores.academicHealth}</span></div>) : <p className="text-sm text-slate-500">No high-risk students in the permitted scope.</p>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Ask ACADLYX</h2><form onSubmit={ask} className="mt-3"><input value={question} onChange={e => setQuestion(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"/><button className="mt-2 rounded-lg bg-acadlyx-primary px-4 py-2 text-sm font-medium text-white">Ask</button></form><div className="mt-3 flex flex-wrap gap-2">{questions.map(q => <button key={q} onClick={() => setQuestion(q)} className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{q}</button>)}</div>{answer && <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium text-slate-900">{answer.answer}</p>{answer.actions.map(a => <p className="mt-1 text-slate-600" key={a}>• {a}</p>)}</div>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section></div><section className="mt-5 rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Recommended actions</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600">{center?.recommendedActions.map(a => <li key={a}>{a}</li>) || <li>No current escalation.</li>}</ul></section></div></main>;
}
