"use client";
import { useEffect,useState } from "react";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { authedFetch,AuthRequiredError } from "@/lib/auth";
import { useRouter } from "next/navigation";

export default function LmsReportsPage(){
 const router=useRouter();const [rows,setRows]=useState<any[]>([]);const [meta,setMeta]=useState<any>();const [page,setPage]=useState(1);const [departmentId,setDepartmentId]=useState("");const [programId,setProgramId]=useState("");const [semesterId,setSemesterId]=useState("");const [sectionId,setSectionId]=useState("");const [error,setError]=useState("");
 useEffect(()=>{void load()},[page,departmentId,programId,semesterId,sectionId]);
 async function load(){try{setError("");const q=new URLSearchParams({page:String(page),pageSize:"20"});for(const [k,v] of Object.entries({departmentId,programId,semesterId,sectionId}))if(v)q.set(k,v);const r=await authedFetch<any>(`/lms/reports?${q.toString()}`);setRows(r.data);setMeta(r.meta)}catch(e){if(e instanceof AuthRequiredError)router.replace("/login");else setError(e instanceof Error?e.message:"Report unavailable")}}
 return <DashboardShell title="LMS Reports" subtitle="Scope-aware course, content, assessment and learning analytics."><div className="mx-auto max-w-7xl space-y-5">{error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}<section className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-4"><input value={departmentId} onChange={e=>{setPage(1);setDepartmentId(e.target.value)}} placeholder="Department ID" className="rounded-xl border p-3"/><input value={programId} onChange={e=>{setPage(1);setProgramId(e.target.value)}} placeholder="Program ID" className="rounded-xl border p-3"/><input value={semesterId} onChange={e=>{setPage(1);setSemesterId(e.target.value)}} placeholder="Semester ID" className="rounded-xl border p-3"/><input value={sectionId} onChange={e=>{setPage(1);setSectionId(e.target.value)}} placeholder="Section ID" className="rounded-xl border p-3"/></section><section className="grid gap-4 md:grid-cols-2">{rows.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-black">{r.code} · {r.name}</h2><span className="text-xs font-bold">{r.lmsStatus}</span></div><p className="mt-1 text-xs text-slate-500">{r.departmentName} · {r.programName} · {r.academicYearName} · {r.semesterName} · {r.sectionName}</p><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><span>Students {r.analytics?.rosterSize??0}</span><span>Lessons {r.analytics?.content?.lessons??0}</span><span>Assignments {r.analytics?.assignments??0}</span><span>Quizzes {r.analytics?.quizzes?.quizzes??0}</span><span>Internal {Math.round(r.analytics?.internalMarks?.avg??0)}%</span><span>Exams {Math.round(r.analytics?.examinations?.avg??0)}%</span></div></article>)}</section><div className="flex items-center justify-between rounded-2xl border bg-white p-4"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="rounded-lg border px-3 py-2">Previous</button><span className="text-sm">Page {meta?.page??page} / {meta?.totalPages??1}</span><button disabled={!meta||page>=meta.totalPages} onClick={()=>setPage(page+1)} className="rounded-lg border px-3 py-2">Next</button></div></div></DashboardShell>
}
