export const JOB_TYPES = {
  ADMIT_CARD_GENERATION: "ADMIT_CARD_GENERATION",
  RESULT_PROCESSING: "RESULT_PROCESSING",
  MARKSHEET_GENERATION: "MARKSHEET_GENERATION",
  BULK_IMPORT: "BULK_IMPORT",
  BULK_EXPORT: "BULK_EXPORT",
  PDF_GENERATION: "PDF_GENERATION",
  REPORT_GENERATION: "REPORT_GENERATION",
  NOTIFICATION_BATCH: "NOTIFICATION_BATCH",
  FEE_PROCESSING: "FEE_PROCESSING",
  LIBRARY_FINE_PROCESSING: "LIBRARY_FINE_PROCESSING",
  DOCUMENT_PROCESSING: "DOCUMENT_PROCESSING",
} as const;
export type JobType = typeof JOB_TYPES[keyof typeof JOB_TYPES];
