"use client";
import { FormEvent, useState } from "react";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { authedFetch } from "@/lib/auth";

const types = ["students","faculty","departments","programs","courses","sections","marks","attendance","fees","notices","timetable"] as const;
const help: Record<string,string> = { students:"email, firstName, lastName, phone, password, rollNumber, programCode, academicYear, section, status", faculty:"email, firstName, lastName, phone, password", departments:"code, name, active", programs:"code, name, departmentCode, level, durationYears", courses:"code, name, departmentCode, credits, description", sections:"name, programCode, academicYear, semesterNumber, capacity, active", marks:"email or rollNumber, courseCode, section, component, marksObtained, maxMarks", attendance:"email or rollNumber, courseCode, section, date, status", fees:"email or rollNumber, title, amount, dueDate, status", notices:"title, body, audience, publishedAt, expiresAt", timetable:"courseCode, section, dayOfWeek, startTime, endTime, room" };
export default function ImportsPage(){ const [type,setType]=useState<(typeof types)[number]>("students"); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<any>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 async function send(e:FormEvent, action:"preview"|"commit"){ e.preventDefault(); if(!file)return setMessage("Choose an Excel/CSV file first."); setBusy(true);setMessage(""); try{const fd=new FormData();fd.append("file",file); const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:5001/api/v1"}/imports/${type}/${action}`,{method:"POST",headers:{Authorization:`Bearer ${localStorage.getItem("acadlyx_access_token")||""}`},body:fd}); const b=await r.json(); if(!r.ok)throw new Error(b?.error?.message||"Import failed"); if(action==="preview")setPreview(b.data); else {setPreview(null);setMessage(`Imported ${b.data.imported} row(s) successfully.`)}}catch(e){setMessage(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 return <DashboardShell title="Data Import Center" subtitle="Bulk-load institutional ERP data safely" allowedRoles={["INSTITUTION_ADMIN","DIRECTOR","MANAGEMENT"]}><div className="mx-auto max-w-6xl"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Bulk data operations</p><h1 className="mt-2 text-2xl font-bold">Excel / CSV Import Center</h1><p className="mt-1 text-sm text-slate-500">Preview first, then commit. Tenant scope comes from the authenticated account.</p></div><form onSubmit={e=>send(e,"preview")} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 md:grid-cols-2"><div><label className="text-sm font-semibold">Data type</label><select value={type} onChange={e=>{setType(e.target.value as any);setPreview(null)}} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm">{types.map(t=><option key={t}>{t}</option>)}</select></div><div><label className="text-sm font-semibold">Spreadsheet</label><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-2 block w-full rounded-xl border border-slate-300 p-2.5 text-sm"/></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs text-slate-600"><b>Expected columns:</b> {help[type]}</div><div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Working…":"Preview"}</button>{preview&&<button type="button" disabled={busy} onClick={()=>send(new Event("submit") as any,"commit")} className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Commit import</button>}</div>{message&&<p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}</form>{preview&&<section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Preview · {preview.totalRows} rows</h2><span className="text-xs text-slate-400">First 10 shown</span></div><div className="mt-4 overflow-auto"><table className="min-w-full text-left text-xs"><thead><tr>{Object.keys(preview.sample?.[0]||{}).map(k=><th key={k} className="border-b px-3 py-2 font-semibold">{k}</th>)}</tr></thead><tbody>{preview.sample?.map((row:any,i:number)=><tr key={i}>{Object.keys(preview.sample?.[0]||{}).map(k=><td key={k} className="border-b px-3 py-2 whitespace-nowrap">{String(row[k]??"")}</td>)}</tr>)}</tbody></table></div></section>}</div></DashboardShell> }


