services:
  - type: web
    name: acadlyx-api
    runtime: node
    rootDir: backend
    plan: 0.5c-512mb
    buildCommand: npm ci && npm run build
    preDeployCommand: npx prisma migrate deploy && npm run prisma:rbac:sync
    startCommand: npm start
    maxShutdownDelaySeconds: 60
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://acadlyx-orcin.vercel.app
      - key: FRONTEND_URL
        value: https://acadlyx-orcin.vercel.app
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN_DAYS
        value: 30
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: AUTH_MAX_FAILED_ATTEMPTS
        value: 8
      - key: AUTH_LOCKOUT_MINUTES
        value: 15
      - key: AUTH_RESET_TTL_MINUTES
        value: 30
      - key: MAIL_ENABLED
        value: "false"
      - key: PAYMENT_PROVIDER
        value: manual
      - key: PAYMENT_CURRENCY
        value: INR
      - key: STORAGE_PROVIDER
        value: cloudinary
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RBAC_SYNC_ON_BOOT
        value: "false"

  - type: worker
    name: acadlyx-worker
    runtime: node
    rootDir: backend
    plan: 0.5c-512mb
    buildCommand: npm ci && npm run build
    startCommand: npm run worker
    maxShutdownDelaySeconds: 120
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: STORAGE_PROVIDER
        value: cloudinary
      - key: CLOUDINARY_URL
        sync: false
      - key: JOB_CONCURRENCY
        value: "2"
      - key: JOB_POLL_MS
        value: "1000"
      - key: JOB_HEARTBEAT_MS
        value: "15000"
      - key: JOB_STALE_MS
        value: "120000"
      - key: JOB_SHUTDOWN_TIMEOUT_MS
        value: "110000"
