"use client";

import { useEffect, useState } from "react";
import { AuthRequiredError, AuthUser, getCurrentUser } from "@/lib/auth";

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-black uppercase tracking-[0.12em] text-slate-700">{title}</h2><div className="mt-4">{children}</div></section>; }
function Item({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-800">{value || "Not provided"}</p></div>; }

export default function MyProfilePage() {
  const [user, setUser] = useState<AuthUser | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let alive = true; getCurrentUser({ background: true }).then(current => { if (alive) setUser(current); }).catch(err => { if (alive) setError(err instanceof AuthRequiredError ? "Your session has expired." : err instanceof Error ? err.message : "Unable to load profile."); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, []);
  if (loading) return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Loading your profile…</div>;
  if (error || !user) return <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error || "Profile unavailable."}</div>;
  return <div className="mx-auto max-w-6xl space-y-5">
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-2xl bg-blue-600 text-2xl font-black text-white shadow-sm">{`${user.firstName?.[0] || ""}${user.lastName?.[0] || ""}`.toUpperCase()}</div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.15em] text-slate-400">360° profile</p><h1 className="mt-1 text-2xl font-black text-slate-950">{user.firstName} {user.lastName}</h1><p className="mt-1 text-sm font-medium text-slate-500">{user.idNumber} · {user.email}</p></div><div className="sm:ml-auto"><span className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-800"><span className="h-1.5 w-1.5 rounded-full bg-amber-500"/>View only</span></div></div><div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm leading-6 text-blue-900"><strong>Profile changes are authority-controlled.</strong> Your profile is a complete read-only record. Personal, account, role, academic and institutional details can only be added or changed by an authorized higher authority.</div></div>
    <div className="grid gap-5 lg:grid-cols-2">
      <Card title="Identity"><div className="grid gap-3 sm:grid-cols-2"><Item label="First name" value={user.firstName}/><Item label="Last name" value={user.lastName}/><Item label="ID number / login ID" value={user.idNumber}/><Item label="Email / login email" value={user.email}/></div></Card>
      <Card title="Institution"><div className="grid gap-3 sm:grid-cols-2"><Item label="Institution ID" value={user.institutionId}/><Item label="Account ID" value={user.id}/><Item label="Account status" value="Active authenticated account"/><Item label="Profile access" value="Read only"/></div></Card>
      <Card title="Authority & access"><div className="space-y-3"><Item label="Roles" value={user.roles.length ? user.roles.join(" · ") : null}/><div className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Permissions</p><div className="mt-2 flex flex-wrap gap-1.5">{user.permissions.length ? user.permissions.map(permission => <span key={permission} className="rounded-full border border-slate-200 bg-white px-2 py-1 text-[11px] font-semibold text-slate-600">{permission}</span>) : <span className="text-sm font-semibold text-slate-500">No permissions returned</span>}</div></div></div></Card>
      <Card title="Security & account"><div className="grid gap-3 sm:grid-cols-2"><Item label="Authentication" value="Managed by ACADLYX authentication"/><Item label="Login identifier" value={user.idNumber || user.email}/><Item label="Password" value="Hidden · authority controlled"/><Item label="Self-editing" value="Disabled"/></div></Card>
    </div>
    <Card title="Authority-controlled changes"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-bold text-slate-800">Identity & contact</p><p className="mt-1 text-xs leading-5 text-slate-500">Names, ID number, login email, phone and other official identity data.</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-bold text-slate-800">Academic / employment</p><p className="mt-1 text-xs leading-5 text-slate-500">Program, department, designation, section, course and institutional records where applicable.</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-bold text-slate-800">Access & security</p><p className="mt-1 text-xs leading-5 text-slate-500">Roles, permissions, login credentials and account status remain controlled by higher authority.</p></div></div></Card>
  </div>;
}
