"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AuthRequiredError, authedFetch, getCachedCurrentUser } from "@/lib/auth";
import { deleteAdminUser, requestAdminUserPermanentDeletion } from "@/lib/adminApi";
import { ModalPortal } from "@/components/ui/ModalPortal";
import { DetailDrawer, DetailField } from "@/components/ui/DetailDrawer";

type Lookup = { id: string; name?: string; code?: string; number?: number; programId?: string; academicYearId?: string; departmentId?: string; semesterId?: string; capacity?: number | null; isActive?: boolean; isCurrent?: boolean; department?: { id: string; name: string; code?: string | null } };
type Student = { id: string; idNumber: string; email: string; firstName: string; lastName: string; phone?: string | null; isActive: boolean; enrollmentState?: "PROFILE_MISSING" | "MISSING" | "INVALID" | "ENROLLED"; profile?: { admissionNumber: string; dateOfBirth?: string | null; gender?: string | null; bloodGroup?: string | null; nationality?: string | null; address?: string | null; city?: string | null; state?: string | null; postalCode?: string | null; guardianName?: string | null; guardianPhone?: string | null; guardianEmail?: string | null; emergencyContactName?: string | null; emergencyContactPhone?: string | null; admissionDate?: string | null; status: string } | null; enrollments?: Enrollment[]; currentEnrollment?: Enrollment | null };
type Enrollment = { id: string; academicYearId: string; programId: string; semesterId?: string | null; sectionId?: string | null; rollNumber?: string | null; status: string; enrolledAt?: string; program?: Lookup; academicYear?: Lookup; semester?: Lookup; section?: Lookup };
type ListResponse<T> = { success?: boolean; data?: T[]; meta?: { total?: number; page?: number; pageSize?: number; totalPages?: number } };
type Props = { onChanged?: () => void | Promise<void>; departmentId?: string };

const statuses = ["ACTIVE", "INACTIVE", "GRADUATED", "WITHDRAWN", "TRANSFERRED"];
const enrollmentStatuses = ["ACTIVE", "COMPLETED", "DROPPED", "TRANSFERRED"];
function inputClass() { return "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-slate-500 focus:ring-2 focus:ring-slate-100 disabled:bg-slate-50"; }
function labelClass() { return "mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500"; }
function dateValue(value?: string | null) {
  if (!value) return "";
  const raw = String(value);
  const dateOnly = raw.match(/^\d{4}-\d{2}-\d{2}/);
  if (dateOnly) return dateOnly[0];
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? raw.slice(0, 10) : new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit" }).format(d);
}
function optionLabel(item: Lookup) { if (item.code && item.name) return `${item.code} — ${item.name}`; if (item.number !== undefined && item.name) return `Semester ${item.number} — ${item.name}`; return item.name || item.code || item.id; }
function statusClass(status: string) { if (status === "ACTIVE") return "bg-emerald-50 text-emerald-700"; if (status === "GRADUATED" || status === "COMPLETED") return "bg-blue-50 text-blue-700"; if (status === "WITHDRAWN" || status === "DROPPED" || status === "TRANSFERRED") return "bg-amber-50 text-amber-700"; return "bg-slate-100 text-slate-600"; }
function Field({ label, children, required }: { label: string; children: ReactNode; required?: boolean }) { return <label><span className={labelClass()}>{label}{required ? " *" : ""}</span>{children}</label>; }
function Section({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4"><h3 className="font-semibold text-slate-950">{title}</h3>{description && <p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>}</div>{children}</section>; }

export function StudentManagement({ onChanged, departmentId }: Props) {
  const [students, setStudents] = useState<Student[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [totalStudents, setTotalStudents] = useState(0); const [permissions, setPermissions] = useState<string[]>([]); const [departments, setDepartments] = useState<Lookup[]>([]); const [programs, setPrograms] = useState<Lookup[]>([]); const [academicYears, setAcademicYears] = useState<Lookup[]>([]); const [semesters, setSemesters] = useState<Lookup[]>([]); const [sections, setSections] = useState<Lookup[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [programFilter, setProgramFilter] = useState(""); const [semesterFilter, setSemesterFilter] = useState(""); const [sectionFilter, setSectionFilter] = useState(""); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Student | null>(null); const [selected, setSelected] = useState<Student | null>(null); const [showEnrollment, setShowEnrollment] = useState(false);
  const emptyForm = { idNumber:"", email:"", firstName:"", lastName:"", phone:"", password:"", admissionNumber:"", dateOfBirth:"", gender:"", bloodGroup:"", nationality:"Indian", address:"", city:"", state:"", postalCode:"", guardianName:"", guardianPhone:"", guardianEmail:"", emergencyContactName:"", emergencyContactPhone:"", admissionDate:"", status:"ACTIVE", programId:"", academicYearId:"", semesterId:"", sectionId:"", rollNumber:"" };
  const [form, setForm] = useState(emptyForm); const [enrollment, setEnrollment] = useState({ academicYearId:"", programId:"", semesterId:"", sectionId:"", rollNumber:"", status:"ACTIVE" });
  const studentFilterReady = useRef(false);
  const loadLookups = useCallback(async () => {
    const [d,y] = await Promise.all([
      departmentId
        ? authedFetch<{data:Lookup}>(`/departments/${encodeURIComponent(departmentId)}`)
        : authedFetch<ListResponse<Lookup>>("/departments?page=1&pageSize=100&isActive=true"),
      authedFetch<ListResponse<Lookup>>("/academic-years?page=1&pageSize=100")
    ]);
    const departmentItems = Array.isArray(d.data) ? d.data : d.data ? [d.data] : [];
    setDepartments(departmentItems);
    setAcademicYears(y.data||[]);
  },[departmentId]);
  const loadPrograms = useCallback(async (departmentId: string) => { if (!departmentId) { setPrograms([]); return []; } const r=await authedFetch<ListResponse<Lookup>>(`/programs?page=1&pageSize=100&isActive=true&departmentId=${encodeURIComponent(departmentId)}`); const items=r.data||[]; setPrograms(items); return items; },[]);
  const loadSemesters = useCallback(async (programId: string, academicYearId: string) => { if (!programId || !academicYearId) { setSemesters([]); return []; } const r=await authedFetch<ListResponse<Lookup>>(`/semesters?page=1&pageSize=100&isActive=true&programId=${encodeURIComponent(programId)}&academicYearId=${encodeURIComponent(academicYearId)}`); const items=r.data||[]; setSemesters(items); return items; },[]);
  const loadSections = useCallback(async (semesterId: string) => { if (!semesterId) { setSections([]); return []; } const r=await authedFetch<ListResponse<Lookup>>(`/sections?page=1&pageSize=100&isActive=true&semesterId=${encodeURIComponent(semesterId)}`); const items=r.data||[]; setSections(items); return items; },[]);
  const loadStudents = useCallback(async () => { setLoading(true); setError(""); try { const params=new URLSearchParams({page:String(page),pageSize:"50"}); if(departmentId) params.set("departmentId",departmentId); else if(departmentFilter) params.set("departmentId",departmentFilter); if(search.trim())params.set("search",search.trim()); if(statusFilter)params.set("status",statusFilter); if(programFilter)params.set("programId",programFilter); if(semesterFilter)params.set("semesterId",semesterFilter); if(sectionFilter)params.set("sectionId",sectionFilter); const response=await authedFetch<ListResponse<Student>>(`/students?${params.toString()}`); const nextStudents=response.data||[]; setStudents(nextStudents); setTotalStudents(response.meta?.total ?? nextStudents.length); setTotalPages(Math.max(1,response.meta?.totalPages ?? 1)); } catch(err){ if(err instanceof AuthRequiredError)throw err; setError(err instanceof Error?err.message:"Unable to load students."); } finally{setLoading(false);} },[search,statusFilter,departmentFilter,programFilter,semesterFilter,sectionFilter,departmentId,page]);
  useEffect(()=>{void(async()=>{try{const currentUser=getCachedCurrentUser();setPermissions(currentUser?.permissions??[]);await Promise.all([loadLookups(),loadStudents(),departmentId ? loadPrograms(departmentId) : Promise.resolve([])]);}catch(err){setError(err instanceof Error?err.message:"Unable to load student management.");}})();},[loadLookups,loadStudents,loadPrograms,departmentId]);
  useEffect(()=>{setPage(1);},[search,statusFilter,departmentFilter,programFilter,semesterFilter,sectionFilter,departmentId]);
  useEffect(()=>{if(!studentFilterReady.current){studentFilterReady.current=true;return;}const timer=window.setTimeout(()=>{void loadStudents();},250);return()=>window.clearTimeout(timer);},[loadStudents]);
  const filteredPrograms=programs;
  const filteredSemesters=semesters;
  const filteredSections=sections;
  const enrollmentSemesters=semesters;
  const enrollmentSections=sections;
  function setField(key:keyof typeof form,value:string){setForm(previous=>({...previous,[key]:value}));}
  function resetForm(){setForm(emptyForm);setEditing(null);setShowForm(false);}
  function startCreate(){setSuccess("");setError("");setEditing(null);setForm({...emptyForm,academicYearId:academicYears.find(x=>x.isCurrent)?.id||""});setShowForm(true);if(departmentId)void loadPrograms(departmentId);}
  async function startEdit(student:Student){const p=student.profile;const e=student.currentEnrollment;setSuccess("");setError("");setEditing(student);setDepartments(current=>current);setForm({idNumber:student.idNumber,email:student.email,firstName:student.firstName,lastName:student.lastName,phone:student.phone||"",password:"",admissionNumber:p?.admissionNumber||"",dateOfBirth:dateValue(p?.dateOfBirth),gender:p?.gender||"",bloodGroup:p?.bloodGroup||"",nationality:p?.nationality||"",address:p?.address||"",city:p?.city||"",state:p?.state||"",postalCode:p?.postalCode||"",guardianName:p?.guardianName||"",guardianPhone:p?.guardianPhone||"",guardianEmail:p?.guardianEmail||"",emergencyContactName:p?.emergencyContactName||"",emergencyContactPhone:p?.emergencyContactPhone||"",admissionDate:dateValue(p?.admissionDate),status:p?.status||"ACTIVE",programId:e?.programId||"",academicYearId:e?.academicYearId||"",semesterId:e?.semesterId||"",sectionId:e?.sectionId||"",rollNumber:e?.rollNumber||""});setShowForm(true);if(e?.program?.department?.id){await loadPrograms(e.program.department.id);if(e.programId&&e.academicYearId){await loadSemesters(e.programId,e.academicYearId);}if(e.semesterId){await loadSections(e.semesterId);}}}
  async function saveStudent(event:FormEvent){event.preventDefault();setSaving(true);setError("");setSuccess("");try{if(!editing){const payload:Record<string,unknown>={...form,password:form.password,sectionId:form.sectionId||""};delete payload.password;payload.password=form.password;await authedFetch("/students",{method:"POST",body:JSON.stringify(payload)});setSuccess("Student account, master profile and first enrollment created successfully.");}else{const payload:Record<string,unknown>={idNumber:form.idNumber,email:form.email,firstName:form.firstName,lastName:form.lastName,phone:form.phone,admissionNumber:form.admissionNumber,dateOfBirth:form.dateOfBirth,gender:form.gender,bloodGroup:form.bloodGroup,nationality:form.nationality,address:form.address,city:form.city,state:form.state,postalCode:form.postalCode,guardianName:form.guardianName,guardianPhone:form.guardianPhone,guardianEmail:form.guardianEmail,emergencyContactName:form.emergencyContactName,emergencyContactPhone:form.emergencyContactPhone,admissionDate:form.admissionDate,status:form.status};await authedFetch(`/students/${editing.id}`,{method:"PATCH",body:JSON.stringify(payload)});if(form.programId&&form.academicYearId&&form.semesterId)await authedFetch(`/students/${editing.id}/enrollments`,{method:"POST",body:JSON.stringify({programId:form.programId,academicYearId:form.academicYearId,semesterId:form.semesterId,sectionId:form.sectionId||"",rollNumber:form.rollNumber,status:"ACTIVE"})});setSuccess("Student profile and academic enrollment updated successfully.");}resetForm();await loadStudents();await onChanged?.();}catch(err){setError(err instanceof Error?err.message:"Unable to save student.");}finally{setSaving(false);}}
  async function softDeleteStudent(student:Student){if(!permissions.includes("users.delete"))return;const confirmed=window.confirm(`Move ${student.firstName} ${student.lastName} to Deleted Users? The account will be disabled and recoverable for 90 days.`);if(!confirmed)return;const reason=window.prompt("Required deletion reason:","")?.trim();if(!reason){setError("A deletion reason is required.");return;}setSaving(true);setError("");setSuccess("");try{await deleteAdminUser(student.id,reason);setStudents(current=>current.filter(item=>item.id!==student.id));setSelected(null);setSuccess("Student moved to Deleted Users. The 90-day recovery period has started.");await onChanged?.();}catch(err){setError(err instanceof Error?err.message:"Unable to delete student.");}finally{setSaving(false);}}
  async function permanentlyDeleteStudent(student:Student){if(!permissions.includes("users.delete"))return;const confirmed=window.confirm(`PERMANENTLY DELETE ${student.firstName} ${student.lastName}?\n\nThis permanently removes the student account and related records allowed by the database relations. This cannot be undone.`);if(!confirmed)return;const reason=window.prompt("Optional permanent deletion reason:","")?.trim()||undefined;setSaving(true);setError("");setSuccess("");try{const result=await requestAdminUserPermanentDeletion(student.id,reason);if(result.permanentlyDeleted){setStudents(current=>current.filter(item=>item.id!==student.id));setSelected(null);setSuccess("Student permanently deleted.");}else setSuccess(result.message||"Permanent deletion request submitted for higher-authority approval.");await onChanged?.();}catch(err){setError(err instanceof Error?err.message:"Unable to permanently delete student.");}finally{setSaving(false);}}
  async function openStudent(student:Student){setError("");try{const response=await authedFetch<{success?:boolean;data?:Student}>(`/students/${student.id}`);setSelected(response.data||student);}catch(err){setError(err instanceof Error?err.message:"Unable to open student.");}}
  async function startEnrollment(student:Student){const e=student.currentEnrollment;const contextDepartmentId=departmentId||e?.program?.department?.id||"";setSelected(student);setEnrollment({academicYearId:academicYears.find(x=>x.isCurrent)?.id||e?.academicYearId||"",programId:e?.programId||"",semesterId:e?.semesterId||"",sectionId:e?.sectionId||"",rollNumber:e?.rollNumber||"",status:"ACTIVE"});setShowEnrollment(true);if(contextDepartmentId){await loadPrograms(contextDepartmentId);if(e.programId&&e.academicYearId){await loadSemesters(e.programId,e.academicYearId);}if(e.semesterId){await loadSections(e.semesterId);}}}
  async function saveEnrollment(event:FormEvent){event.preventDefault();if(!selected)return;setSaving(true);setError("");setSuccess("");try{await authedFetch(`/students/${selected.id}/enrollments`,{method:"POST",body:JSON.stringify({...enrollment,sectionId:enrollment.sectionId||""})});const response=await authedFetch<{success?:boolean;data?:Student}>(`/students/${selected.id}`);const authoritative=response.data||selected;setSelected(authoritative);setShowEnrollment(false);setSuccess("Academic enrollment updated successfully.");await loadStudents();await onChanged?.();}catch(err){setError(err instanceof Error?err.message:"Unable to save enrollment.");}finally{setSaving(false);}}

  function EnrollmentRowAction({ student, onOpen }: { student: Student; onOpen: (student: Student) => void }) {