"use client";

import { ReactNode, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";

export type DashboardNavigationItem = { label:string; href:string; icon?:string; group?:string; badge?:string|number; children?:DashboardNavigationItem[] };
const icons:Record<string,string>={home:"M4 10.5 12 4l8 6.5M6.5 9v9h11V9",people:"M16 20v-1.5a3.5 3.5 0 0 0-3.5-3.5h-5A3.5 3.5 0 0 0 4 18.5V20M10 11a3.5 3.5 0 1 0 0-7",student:"M12 14a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21a8 8 0 0 1 16 0",academic:"M3 7.5 12 3l9 4.5-9 4.5-9-4.5ZM6 10.5V17c3.5 2.5 8.5 2.5 12 0v-6.5",calendar:"M5 4v3M19 4v3M4 8.5h16M6.5 3.5h11A2.5 2.5 0 0 1 20 6v12.5",settings:"M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7ZM19 12l2-2-2-3-2.4 1a8 8 0 0 0-2-1.2L14 3h-4l-.3 2.8a8 8 0 0 0-2 1.2l-2.4-1-2 3 2 2",logout:"M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-5",menu:"M4 7h16M4 12h16M4 17h16"};
export function SvgIcon({name,className="h-[18px] w-[18px]"}:{name?:string;className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className}><path d={icons[name||"home"]||icons.home}/></svg>;}
function active(pathname:string,href:string){return pathname===href||pathname.startsWith(`${href}/`);}
function flatten(items:DashboardNavigationItem[]):DashboardNavigationItem[]{return items.flatMap((item)=>[item,...(item.children?flatten(item.children):[])]);}
function Brand({logoUrl,institutionLogoUrl,collapsed}:{logoUrl?:string|null;institutionLogoUrl?:string|null;collapsed:boolean}){return <div className={collapsed?"flex justify-center":"flex items-center gap-2.5"}><div className="grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-white ring-1 ring-slate-200">{logoUrl?<img src={logoUrl} alt="ACADLYX logo" className="h-full w-full object-contain"/>:<span className="font-black text-blue-600">A</span>}</div>{!collapsed?<div className="grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-white ring-1 ring-slate-200">{institutionLogoUrl?<img src={institutionLogoUrl} alt="Institution logo" className="h-full w-full object-contain"/>:<span className="text-[10px] font-black text-slate-500">IN</span>}</div>:null}</div>;}
export function UnifiedDashboardFrame({children,navigation=[],title,subtitle,userName,userRole,institutionName,logoUrl,institutionLogoUrl,onSignOut}:{children:ReactNode;navigation?:DashboardNavigationItem[];title?:string;subtitle?:string;userName?:string;userRole?:string;userEmail?:string;institutionName?:string;logoUrl?:string|null;institutionLogoUrl?:string|null;onSignOut?:()=>void|Promise<void>;}){
 const pathname=usePathname();const router=useRouter();const[collapsed,setCollapsed]=useState(false);const[mobile,setMobile]=useState(false);const[menu,setMenu]=useState(false);
 const groups=useMemo(()=>{const m=new Map<string,DashboardNavigationItem[]>();for(const item of navigation){const key=item.group||"Workspace";m.set(key,[...(m.get(key)||[]),item]);}return [...m.entries()];},[navigation]);
 const initials=useMemo(()=>{const p=(userName||"User").trim().split(/\s+/);return ((p[0]?.[0]||"U")+(p.length>1?(p[p.length-1]?.[0]||""):"")).toUpperCase();},[userName]);
 useEffect(()=>setMobile(false),[pathname]);
 async function signOut(){await onSignOut?.();router.replace("/");}
 return <div className="min-h-screen bg-[#f5efe4] text-slate-950">
  <aside className={`fixed inset-y-0 left-0 z-[80] hidden border-r border-white/10 bg-[#101a2d] p-3 lg:block ${collapsed?"w-[82px]":"w-[264px]"} transition-all`}><div className="flex h-14 items-center justify-center"><Brand logoUrl={logoUrl} institutionLogoUrl={institutionLogoUrl} collapsed={collapsed}/></div><nav className="mt-5 space-y-5 overflow-y-auto pb-20">{groups.map(([group,items])=><div key={group}><p className={`mb-2 px-2 text-[9px] font-black uppercase tracking-[0.18em] text-slate-500 ${collapsed?"sr-only":""}`}>{group}</p><div className="space-y-1">{items.map(item=><Link key={item.href+item.label} href={item.href} title={collapsed?item.label:undefined} className={`flex min-h-11 items-center gap-3 rounded-xl px-2.5 text-sm font-semibold transition ${active(pathname,item.href)?"bg-blue-600 text-white":"text-slate-300 hover:bg-white/10 hover:text-white"} ${collapsed?"justify-center":""}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-white/5"><SvgIcon name={item.icon}/></span>{!collapsed?<span className="truncate">{item.label}</span>:null}</Link>)}</div></div>)}</nav><button onClick={()=>setCollapsed(v=>!v)} className="absolute bottom-4 left-3 right-3 rounded-xl bg-white/5 px-3 py-2 text-xs font-bold text-slate-300">{collapsed?"→":"← Collapse"}</button></aside>
  {mobile?<div className="fixed inset-0 z-[90] bg-slate-950/40 lg:hidden" onClick={()=>setMobile(false)}><aside onClick={e=>e.stopPropagation()} className="h-full w-[285px] bg-[#101a2d] p-4 text-white"><Brand logoUrl={logoUrl} institutionLogoUrl={institutionLogoUrl} collapsed={false}/><nav className="mt-7 space-y-1">{flatten(navigation).map(item=><Link key={item.href+item.label} href={item.href} onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${active(pathname,item.href)?"bg-blue-600":"text-slate-300"}`}><SvgIcon name={item.icon}/>{item.label}</Link>)}</nav></aside></div>:null}
  <div className={`transition-[margin] duration-200 ${collapsed?"lg:ml-[82px]":"lg:ml-[264px]"}`}><header className="sticky top-0 z-50 border-b border-[#d8d0c4] bg-[#fbf8f2]/95 backdrop-blur-xl"><div className="flex min-h-[72px] items-center justify-between gap-4 px-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setMobile(true)} className="grid h-10 w-10 place-items-center rounded-xl hover:bg-[#eee7dc] lg:hidden" aria-label="Open navigation"><SvgIcon name="menu"/></button><div className="hidden lg:block"><Brand logoUrl={logoUrl} institutionLogoUrl={institutionLogoUrl} collapsed={false}/></div><div className="min-w-0"><h1 className="truncate text-base font-black">{title||"ACADLYX"}</h1>{(subtitle||institutionName)?<p className="hidden truncate text-[11px] font-semibold text-slate-500 sm:block">{subtitle||institutionName}</p>:null}</div></div><div className="relative"><button onClick={()=>setMenu(v=>!v)} className="flex items-center gap-2 rounded-xl px-2 py-1.5 hover:bg-[#eee7dc]"><span className="grid h-9 w-9 place-items-center rounded-full bg-blue-600 text-xs font-black text-white">{initials}</span><span className="hidden text-left md:block"><b className="block max-w-40 truncate text-xs">{userName||"User"}</b><span className="block text-[10px] font-semibold text-slate-400">{userRole||"Account"}</span></span></button>{menu?<div className="absolute right-0 top-12 z-50 w-52 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><div className="px-3 py-2 text-xs font-bold text-slate-500">{institutionName||""}</div><button onClick={signOut} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-red-600 hover:bg-red-50"><SvgIcon name="logout"/>Logout</button></div>:null}</div></div></header><main className="min-h-[calc(100vh-72px)] p-4 sm:p-6 lg:p-8">{children}</main></div>
 </div>;
}
