"use client";

import { useEffect,useState } from "react";
import { apiFetch,ApiRequestError } from "@/lib/api";
import { DashboardShell } from "@/components/dashboard/DashboardShell";

type Student={id:string;firstName:string;lastName:string;placementProfile:{placementStatus:string}|null;studentEnrollments:Array<{program:{name:string};semester:{name:string}|null}>;_count:{placementApplicationsOwned:number;placementOffers:number}};
type Metrics=Record<string,unknown>;

export default function FacultyPlacementsPage(){
 const [students,setStudents]=useState<Student[]>([]);const[m,setM]=useState<Metrics|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
 useEffect(()=>{void Promise.all([apiFetch<{data:Student[]}>("/placements/students?pageSize=50"),apiFetch<{data:Metrics}>("/placements/metrics")]).then(([s,x])=>{setStudents(s.data||[]);setM(x.data)}).catch(e=>setError(e instanceof ApiRequestError?e.message:"Unable to load placement support workspace.")).finally(()=>setLoading(false));},[]);
 return <DashboardShell title="Student Placement Support" subtitle="Placement readiness and relevant student outcomes within assigned academic scope" allowedRoles={["FACULTY"]}><div className="mx-auto max-w-6xl space-y-6">{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<section className="grid gap-4 sm:grid-cols-3">{[["Students in scope",students.length],["Applications",m?.applications],["Placed",m?.placedStudents]].map(([a,b])=><article key={String(a)} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{a}</p><p className="mt-2 text-2xl font-black">{loading?"—":String(b??0)}</p></article>)}</section><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Placement readiness</h2><p className="mt-1 text-sm text-slate-500">Only students belonging to classes/sections taught by you are returned by the server.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{students.map(s=><article key={s.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-black">{s.firstName} {s.lastName}</p><p className="text-sm text-slate-600">{s.studentEnrollments[0]?.program.name||"Program"} · {s.studentEnrollments[0]?.semester?.name||"Semester"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{s.placementProfile?.placementStatus||"SEEKING"}</span></div><div className="mt-3 flex gap-4 text-xs font-bold text-slate-500"><span>Applications: {s._count.placementApplicationsOwned}</span><span>Offers: {s._count.placementOffers}</span></div></article>)}{!loading&&!students.length&&<p className="py-8 text-center text-sm text-slate-500 md:col-span-2">No placement students are currently within your teaching scope.</p>}</div></section></div></DashboardShell>;
}
