import { createHash } from "crypto";

function escapePdfText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function ascii(value: unknown): string {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "?");
}

/**
 * Dependency-free, deterministic A4 PDF generator for admit cards.
 *
 * Keeping this generator dependency-free makes document generation safe on
 * Render/Vercel environments where native PDF binaries are undesirable.
 * The same data contract can later be rendered by a richer template engine.
 */
export function createAdmitCardPdf(input: {
  institutionName: string;
  institutionAddress?: string | null;
  examination: string;
  sessionCode: string;
  serialNumber: string;
  studentName: string;
  rollNumber?: string | null;
  enrollmentNumber?: string | null;
  program?: string | null;
  department?: string | null;
  semester?: string | null;
  papers: Array<{
    code: string;
    name: string;
    date: string;
    startTime: string;
    endTime: string;
    room: string;
    seat: string;
  }>;
  instructions?: string | null;
}): Buffer {
  const lines: Array<{ text: string; x: number; y: number; size: number; bold?: boolean }> = [];
  const add = (text: unknown, x: number, y: number, size: number, bold = false) =>
    lines.push({ text: ascii(text), x, y, size, bold });

  add(input.institutionName, 50, 790, 18, true);
  add(input.institutionAddress ?? "", 50, 768, 9);
  add("ADMIT CARD", 240, 735, 16, true);
  add(input.examination, 50, 710, 12, true);
  add(`Session: ${input.sessionCode}`, 50, 690, 9);
  add(`Admit Card No.: ${input.serialNumber}`, 390, 690, 9, true);

  const details = [
    ["Student", input.studentName],
    ["Roll Number", input.rollNumber],
    ["Enrollment", input.enrollmentNumber],
    ["Program", input.program],
    ["Department", input.department],
    ["Semester", input.semester],
  ];
  let y = 650;
  for (const [label, value] of details) {
    if (value) {
      add(`${label}: ${value}`, 55, y, 10);
      y -= 20;
    }
  }

  y -= 5;
  add("EXAMINATION SCHEDULE", 50, y, 11, true);
  y -= 24;

  const columns = [
    ["Subject", 50],
    ["Date", 220],
    ["Time", 285],
    ["Room", 380],
    ["Seat", 470],
  ] as const;
  for (const [label, x] of columns) add(label, x, y, 8, true);
  y -= 16;

  for (const paper of input.papers.slice(0, 16)) {
    add(`${paper.code} - ${paper.name}`.slice(0, 35), 50, y, 7);
    add(paper.date, 220, y, 7);
    add(`${paper.startTime}-${paper.endTime}`, 285, y, 7);
    add(paper.room, 380, y, 7);
    add(paper.seat, 470, y, 7);
    y -= 16;
  }

  y = Math.max(y - 18, 95);
  add("IMPORTANT INSTRUCTIONS", 50, y, 10, true);
  y -= 17;
  const instructions = ascii(input.instructions || "Carry this admit card and a valid institutional identity card to every examination.");
  for (const chunk of instructions.match(/.{1,95}/g) ?? []) {
    add(chunk, 55, y, 8);
    y -= 12;
  }

  add("Controller of Examinations", 420, 70, 8, true);
  add("Generated by ACADLYX", 50, 35, 7);

  const objects: string[] = [];
  const offsets: number[] = [0];
  const content = [
    "q",
    "0.7 w",
    "50 55 495 705 re S",
    "50 675 495 0.5 re f",
    "50 600 495 0.5 re f",
    "50 560 495 0.5 re f",
    ...lines.map((line) => `BT /${line.bold ? "F2" : "F1"} ${line.size} Tf ${line.x} ${line.y} Td (${escapePdfText(line.text)}) Tj ET`),
    "Q",
  ].join("\n");

  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  objects.push("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
  objects.push("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>");
  objects.push(`<< /Length ${Buffer.byteLength(content, "latin1")} >>\nstream\n${content}\nendstream`);
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  let output = "%PDF-1.4\n";
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(output, "latin1"));
    output += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xref = Buffer.byteLength(output, "latin1");
  output += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index <= objects.length; index += 1) {
    output += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  output += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /ID [<${createHash("sha256").update(output).digest("hex").slice(0, 32)}> <${createHash("sha256").update(output).digest("hex").slice(0, 32)}>] >>\nstartxref\n${xref}\n%%EOF\n`;

  const buffer = Buffer.from(output, "latin1");
  if (buffer.length < 500 || !buffer.subarray(0, 8).toString("ascii").startsWith("%PDF-1.")) {
    throw new Error("Admit card PDF generation produced an invalid document.");
  }
  return buffer;
}
