import { Prisma } from "@prisma/client";
import { prisma } from "../lib/prisma";
import { AppError } from "../middleware/errorHandler";
import { AuthenticatedUser } from "../types/auth";
import { getCanonicalRoleNames } from "../config/rbac";
import { recordAuditLog } from "./audit.service";
import { makeFile } from "./export.service";

type Scope={institutionId:string;studentIds?:string[];departmentIds?:string[];campusIds?:string[]};
const has=(a:AuthenticatedUser,p:string)=>a.permissions.includes(p);
const rs=(a:AuthenticatedUser)=>getCanonicalRoleNames(a.roles);

async function scope(institutionId:string,a:AuthenticatedUser):Promise<Scope>{
 const r=rs(a);
 if(r.includes("STUDENT")) return {institutionId,studentIds:[a.id]};
 if(r.includes("PARENT")) return {institutionId,studentIds:(await prisma.parentStudentLink.findMany({where:{institutionId,parentId:a.id},select:{studentId:true}})).map(x=>x.studentId)};
 if(r.includes("HOD")||r.includes("DEAN")) return {institutionId,departmentIds:(await prisma.departmentAccess.findMany({where:{userId:a.id,department:{institutionId}},select:{departmentId:true}})).map(x=>x.departmentId)};
 if(r.includes("DIRECTOR")) return {institutionId,campusIds:Array.from(new Set((await prisma.departmentAccess.findMany({where:{userId:a.id,department:{institutionId}},select:{department:{select:{campusId:true}}}})).map(x=>x.department.campusId).filter((x):x is string=>!!x)))};
 if(r.includes("ACCOUNTS")||r.includes("CHAIRMAN")||has(a,"fees.manage")||has(a,"fees.read")) return {institutionId};
 throw new AppError("Financial scope is not authorized",403);
}
function invoiceWhere(s:Scope):Prisma.FeeInvoiceWhereInput{
 if(s.studentIds)return{institutionId:s.institutionId,studentId:{in:s.studentIds}};
 if(s.departmentIds)return{institutionId:s.institutionId,student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}};
 if(s.campusIds)return{institutionId:s.institutionId,student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}};
 return{institutionId:s.institutionId};
}
function paymentWhere(s:Scope):Prisma.FeePaymentWhereInput{return{institutionId:s.institutionId,invoice:s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}:s.campusIds?{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{}}}
function dec(v:unknown){const x=new Prisma.Decimal(String(v??"0"));if(x.lte(0))throw new AppError("Amount must be greater than zero",400);return x}
async function audit(institutionId:string,userId:string,action:string,entityType:string,entityId:string,metadata?:unknown){await recordAuditLog({institutionId,userId,action,entityType,entityId,metadata})}

export async function overview(institutionId:string,a:AuthenticatedUser){
 if(!has(a,"fees.read")&&!has(a,"fees.collection.read"))throw new AppError("Financial visibility permission required",403);
 const s=await scope(institutionId,a),[invoices,payments]=await Promise.all([
  prisma.feeInvoice.findMany({where:invoiceWhere(s),select:{amount:true,paidAmount:true,refundedAmount:true,dueDate:true,status:true}}),
  prisma.feePayment.findMany({where:paymentWhere(s),select:{amount:true,paidAt:true,status:true}})
 ]);
 const now=new Date(),today=new Date(now);today.setHours(0,0,0,0),month=new Date(now.getFullYear(),now.getMonth(),1);
 const billed=invoices.reduce((n,x)=>n+Number(x.amount),0),collected=payments.filter(x=>x.status==="SUCCESS").reduce((n,x)=>n+Number(x.amount),0),refunded=invoices.reduce((n,x)=>n+Number(x.refundedAmount),0);
 const outstanding=Math.max(0,billed-collected-refunded);
 const overdue=invoices.filter(x=>x.dueDate&&x.dueDate<now).reduce((n,x)=>n+Math.max(0,Number(x.amount)-Number(x.paidAmount)-Number(x.refundedAmount)),0);
 return {billed,collected,refunded,outstanding,overdue,collectionPercentage:billed?collected/billed*100:0,todayCollection:payments.filter(x=>x.status==="SUCCESS"&&x.paidAt>=today).reduce((n,x)=>n+Number(x.amount),0),monthCollection:payments.filter(x=>x.status==="SUCCESS"&&x.paidAt>=month).reduce((n,x)=>n+Number(x.amount),0),invoiceCount:invoices.length,paymentCount:payments.length,scope:s};
}
export async function invoices(institutionId:string,a:AuthenticatedUser,input:{studentId?:string;status?:string;search?:string;page?:number;pageSize?:number}){
 const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.invoice.read"))throw new AppError("Invoice visibility permission required",403);
 if(input.studentId&&s.studentIds&&!s.studentIds.includes(input.studentId))throw new AppError("Student is outside your scope",403);
 const page=Math.max(1,input.page||1),size=Math.min(100,Math.max(1,input.pageSize||25));
 const where:Prisma.FeeInvoiceWhereInput={...invoiceWhere(s),...(input.studentId?{studentId:input.studentId}:{}),...(input.status?{status:input.status}:{}),...(input.search?{OR:[{title:{contains:input.search,mode:"insensitive"}},{invoiceNumber:{contains:input.search,mode:"insensitive"}}]}:{})};
 const [items,total]=await Promise.all([prisma.feeInvoice.findMany({where,include:{student:{select:{id:true,firstName:true,lastName:true,email:true,profile:{select:{admissionNumber:true}}}},payments:true,items:{include:{feeHead:true}},concessions:true,refunds:true,receipts:true},orderBy:{createdAt:"desc"},skip:(page-1)*size,take:size}),prisma.feeInvoice.count({where})]);
 return{items,total,page,pageSize:size};
}
export async function invoice(institutionId:string,a:AuthenticatedUser,id:string){
 const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.invoice.read"))throw new AppError("Invoice visibility permission required",403);
 const x=await prisma.feeInvoice.findFirst({where:{id,...invoiceWhere(s)},include:{student:{select:{id:true,firstName:true,lastName:true,email:true,profile:{select:{admissionNumber:true}}}},items:{include:{feeHead:true}},payments:true,concessions:true,refunds:true,receipts:true}});
 if(!x)throw new AppError("Invoice not found in authorized scope",404);return x;
}
async function invoiceNo(institutionId:string){return `INV-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,10).toUpperCase()}`}
async function receiptNo(){return `RCT-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,10).toUpperCase()}`}
export async function createInvoice(institutionId:string,a:AuthenticatedUser,input:any){
 if(!has(a,"fees.invoice.manage"))throw new AppError("Invoice management permission required",403);
 const s=await scope(institutionId,a),student=await prisma.user.findFirst({where:{id:input.studentId,institutionId,userRoles:{some:{role:{name:"STUDENT"}}},...(s.studentIds?{id:{in:s.studentIds}}:s.departmentIds?{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}:s.campusIds?{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}:{})},select:{id:true}});
 if(!student)throw new AppError("Student is outside your financial scope",403);
 const amount=dec(input.amount),items=(input.items||[]).map((x:any)=>({description:String(x.description).trim(),amount:dec(x.amount),feeHeadId:x.feeHeadId||null}));
 const total=items.reduce((n:any,x:any)=>n.plus(x.amount),new Prisma.Decimal(0));if(items.length&&!total.eq(amount))throw new AppError("Invoice amount must equal line items",400);
 const created=await prisma.$transaction(async tx=>{const i=await tx.feeInvoice.create({data:{institutionId,studentId:student.id,title:String(input.title).trim(),amount:Number(amount),grossAmount:Number(amount),dueDate:input.dueDate?new Date(input.dueDate):null,status:"PENDING",feeStructureId:input.feeStructureId||null,academicYearId:input.academicYearId||null,semesterId:input.semesterId||null,createdById:a.id,invoiceNumber:await invoiceNo(institutionId),items:{create:items}}});await tx.feeTransaction.create({data:{institutionId,studentId:student.id,invoiceId:i.id,amount,type:"INVOICE",createdById:a.id}});return i});
 await audit(institutionId,a.id,"finance.invoice.create","FeeInvoice",created.id,{amount:amount.toString(),studentId:student.id});return invoice(institutionId,a,created.id);
}
export async function payment(institutionId:string,a:AuthenticatedUser,id:string,input:any){
 if(!has(a,"fees.payment.record"))throw new AppError("Payment recording permission required",403);
 const s=await scope(institutionId,a),inv=await prisma.feeInvoice.findFirst({where:{id,...invoiceWhere(s)},select:{id:true,studentId:true,amount:true,paidAmount:true,refundedAmount:true}});
 if(!inv)throw new AppError("Invoice not found in authorized scope",404);const amount=dec(input.amount);
 const existing=await prisma.feePayment.findFirst({where:{institutionId,idempotencyKey:String(input.idempotencyKey)}});if(existing)return invoice(institutionId,a,id);
 const result=await prisma.$transaction(async tx=>{const fresh=await tx.feeInvoice.findUnique({where:{id},select:{studentId:true,amount:true,paidAmount:true,refundedAmount:true}});if(!fresh)throw new AppError("Invoice not found",404);const balance=new Prisma.Decimal(fresh.amount).minus(fresh.paidAmount).minus(fresh.refundedAmount);if(amount.gt(balance))throw new AppError("Payment exceeds outstanding balance",409);
  const p=await tx.feePayment.create({data:{institutionId,invoiceId:id,amount:Number(amount),reference:input.reference||null,paidAt:input.paidAt?new Date(input.paidAt):new Date(),method:String(input.method||"OFFLINE"),status:"SUCCESS",recordedById:a.id,userId:a.id,notes:input.notes||null,idempotencyKey:String(input.idempotencyKey)}});
  const paid=new Prisma.Decimal(fresh.paidAmount).plus(amount),status=paid.gte(new Prisma.Decimal(fresh.amount).minus(fresh.refundedAmount))?"PAID":"PARTIALLY_PAID";
  await tx.feeInvoice.update({where:{id},data:{paidAmount:Number(paid),status}});await tx.feeTransaction.create({data:{institutionId,studentId:fresh.studentId,invoiceId:id,paymentId:p.id,amount,type:"PAYMENT",reference:input.reference||null,createdById:a.id}});
  const r=await tx.feeReceipt.create({data:{institutionId,paymentId:p.id,invoiceId:id,studentId:fresh.studentId,receiptNumber:await receiptNo(),issuedById:a.id}});await tx.feePayment.update({where:{id:p.id},data:{receiptNumber:r.receiptNumber}});return p;});
 await audit(institutionId,a.id,"finance.payment.record","FeePayment",result.id,{invoiceId:id,amount:amount.toString(),method:input.method});return invoice(institutionId,a,id);
}
export async function listPayments(institutionId:string,a:AuthenticatedUser){const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.payment.read"))throw new AppError("Payment visibility permission required",403);return prisma.feePayment.findMany({where:paymentWhere(s),include:{invoice:{select:{id:true,invoiceNumber:true,title:true,amount:true,paidAmount:true,status:true,student:{select:{firstName:true,lastName:true,profile:{select:{admissionNumber:true}}}}}}},orderBy:{paidAt:"desc"},take:500})}
export async function listReceipts(institutionId:string,a:AuthenticatedUser){const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.receipt.read"))throw new AppError("Receipt visibility permission required",403);return prisma.feeReceipt.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},include:{payment:true,invoice:{select:{invoiceNumber:true,title:true,amount:true}},student:{select:{firstName:true,lastName:true,profile:{select:{admissionNumber:true}}}}},orderBy:{issuedAt:"desc"},take:500})}
export async function collections(institutionId:string,a:AuthenticatedUser){if(!has(a,"fees.collection.read")&&!has(a,"fees.read"))throw new AppError("Collection visibility permission required",403);const s=await scope(institutionId,a);const rows=await prisma.feeInvoice.findMany({where:invoiceWhere(s),select:{amount:true,paidAmount:true,refundedAmount:true,student:{select:{studentEnrollments:{where:{status:"ACTIVE"},select:{program:{select:{department:{select:{id:true,name:true,code:true,campusId:true}}}}}}}}}}});const map=new Map<string,any>();for(const x of rows)for(const e of x.student.studentEnrollments){const d=e.program.department,r=map.get(d.id)||{departmentId:d.id,name:d.name,billed:0,collected:0,outstanding:0};r.billed+=Number(x.amount);r.collected+=Number(x.paidAmount)-Number(x.refundedAmount);r.outstanding+=Math.max(0,Number(x.amount)-Number(x.paidAmount)-Number(x.refundedAmount));map.set(d.id,r)}return{departments:[...map.values()].sort((a,b)=>b.collected-a.collected),scope:s}}
export async function concessions(institutionId:string,a:AuthenticatedUser){const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.concession.read"))throw new AppError("Concession visibility permission required",403);return prisma.feeConcession.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},orderBy:{createdAt:"desc"},take:500})}
export async function refunds(institutionId:string,a:AuthenticatedUser){const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.refund.read"))throw new AppError("Refund visibility permission required",403);return prisma.feeRefund.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},orderBy:{createdAt:"desc"},take:500})}
export async function requestRefund(institutionId:string,a:AuthenticatedUser,paymentId:string,input:any){if(!has(a,"fees.refund.request"))throw new AppError("Refund request permission required",403);const s=await scope(institutionId,a),p=await prisma.feePayment.findFirst({where:{id:paymentId,...paymentWhere(s)},select:{id:true,invoiceId:true,amount:true,refundedAmount:true,invoice:{select:{studentId:true}}}});if(!p)throw new AppError("Payment not found in authorized scope",404);const amount=dec(input.amount),used=await prisma.feeRefund.aggregate({where:{paymentId,status:{in:["REQUESTED","APPROVED","PROCESSED"]}},_sum:{amount:true}}),available=new Prisma.Decimal(p.amount).minus(p.refundedAmount).minus(used._sum.amount||0);if(amount.gt(available))throw new AppError("Refund exceeds refundable amount",409);return prisma.feeRefund.create({data:{institutionId,paymentId,invoiceId:p.invoiceId,studentId:p.invoice.studentId,amount,reason:String(input.reason).trim(),status:has(a,"fees.refund.approve")?"APPROVED":"REQUESTED",requestedById:a.id,approvedById:has(a,"fees.refund.approve")?a.id:null,approvedAt:has(a,"fees.refund.approve")?new Date():null}})}
export async function approveRefund(institutionId:string,a:AuthenticatedUser,id:string){if(!has(a,"fees.refund.approve"))throw new AppError("Refund approval permission required",403);const x=await prisma.feeRefund.findFirst({where:{id,institutionId,status:"REQUESTED"}});if(!x)throw new AppError("Refund request not found",404);return prisma.feeRefund.update({where:{id},data:{status:"APPROVED",approvedById:a.id,approvedAt:new Date()}})}
export async function processRefund(institutionId:string,a:AuthenticatedUser,id:string){if(!has(a,"fees.refund.process"))throw new AppError("Refund processing permission required",403);return prisma.$transaction(async tx=>{const r=await tx.feeRefund.findFirst({where:{id,institutionId,status:"APPROVED"}});if(!r)throw new AppError("Approved refund not found",404);const p=await tx.feePayment.findUnique({where:{id:r.paymentId},select:{amount:true,refundedAmount:true,invoiceId:true}});if(!p)throw new AppError("Payment not found",404);const next=new Prisma.Decimal(p.refundedAmount).plus(r.amount);if(next.gt(p.amount))throw new AppError("Refund exceeds payment",409);await tx.feePayment.update({where:{id:r.paymentId},data:{refundedAmount:Number(next)}});const i=await tx.feeInvoice.findUnique({where:{id:r.invoiceId},select:{amount:true,paidAmount:true,refundedAmount:true}});if(!i)throw new AppError("Invoice not found",404);const paid=new Prisma.Decimal(i.paidAmount).minus(r.amount),status=paid.lte(0)?"PENDING":paid.lt(i.amount)?"PARTIALLY_PAID":"PAID";await tx.feeInvoice.update({where:{id:r.invoiceId},data:{refundedAmount:Number(new Prisma.Decimal(i.refundedAmount).plus(r.amount)),paidAmount:Number(paid),status}});await tx.feeRefund.update({where:{id},data:{status:"PROCESSED",processedById:a.id,processedAt:new Date()}});await tx.feeTransaction.create({data:{institutionId,studentId:r.studentId,invoiceId:r.invoiceId,paymentId:r.paymentId,amount:r.amount.negated(),type:"REFUND",reference:id,createdById:a.id}});return tx.feeRefund.findUnique({where:{id}})})}
export async function transactions(institutionId:string,a:AuthenticatedUser){const s=await scope(institutionId,a);if(!has(a,"fees.read")&&!has(a,"fees.payment.read"))throw new AppError("Transaction visibility permission required",403);return prisma.feeTransaction.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},orderBy:{createdAt:"desc"},take:500})}

export async function exportFinancial(institutionId:string,a:AuthenticatedUser,type:string,format:"xlsx"|"csv"){if(!has(a,"fees.reports.export")&&!has(a,"fees.read"))throw new AppError("Financial export permission required",403);const s=await scope(institutionId,a);let rows:any[]=[];if(type==="invoices"){const xs=await prisma.feeInvoice.findMany({where:invoiceWhere(s),include:{student:{include:{profile:true}},payments:true},orderBy:{createdAt:"desc"}});rows=xs.map(x=>({invoiceNumber:x.invoiceNumber,title:x.title,student:x.student.email,admissionNumber:x.student.profile?.admissionNumber||null,amount:Number(x.amount),paid:Number(x.paidAmount),refunded:Number(x.refundedAmount),outstanding:Math.max(0,Number(x.amount)-Number(x.paidAmount)-Number(x.refundedAmount)),status:x.status,dueDate:x.dueDate?.toISOString()||null}));}else if(type==="payments"){const xs=await prisma.feePayment.findMany({where:paymentWhere(s),include:{invoice:{include:{student:{include:{profile:true}}}}},orderBy:{paidAt:"desc"}});rows=xs.map(x=>({receipt:x.receiptNumber||null,invoice:x.invoice.invoiceNumber||null,student:x.invoice.student.email,admissionNumber:x.invoice.student.profile?.admissionNumber||null,amount:Number(x.amount),method:x.method,reference:x.reference||null,status:x.status,paidAt:x.paidAt.toISOString()}));}else if(type==="receipts"){const xs=await prisma.feeReceipt.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},include:{payment:true,invoice:true,student:true},orderBy:{issuedAt:"desc"}});rows=xs.map(x=>({receiptNumber:x.receiptNumber,invoiceNumber:x.invoice.invoiceNumber,student:x.student.email,amount:Number(x.payment.amount),method:x.payment.method,issuedAt:x.issuedAt.toISOString()}));}else if(type==="transactions"){const xs=await prisma.feeTransaction.findMany({where:{institutionId,...(s.studentIds?{studentId:{in:s.studentIds}}:s.departmentIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{departmentId:{in:s.departmentIds}}}}}}}:s.campusIds?{invoice:{student:{studentEnrollments:{some:{status:"ACTIVE",program:{department:{campusId:{in:s.campusIds}}}}}}}:{} )},orderBy:{createdAt:"desc"}});rows=xs.map(x=>({type:x.type,amount:Number(x.amount),reference:x.reference||null,invoiceId:x.invoiceId||null,studentId:x.studentId||null,createdAt:x.createdAt.toISOString()}));}else throw new AppError("Unsupported financial export type",400);return makeFile(rows,type as any,format)}
