"use client";
import {useEffect,useState} from "react";
import {financeInvoices,financeOverview,financePayments,financeReceipts} from "@/lib/financeApi";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(n||0));
export default function StudentFinancePage(){const[d,setD]=useState<any>({});const[loading,setLoading]=useState(true);const[error,setError]=useState("");
useEffect(()=>{Promise.all([financeOverview(),financeInvoices({pageSize:100}),financePayments(),financeReceipts()]).then(([o,i,p,r])=>setD({o,i,p,r})).catch(e=>setError(e instanceof Error?e.message:"Unable to load fees")).finally(()=>setLoading(false))},[]);
if(loading)return <main className="min-h-screen bg-[#f6f0e5] p-6 text-center text-sm text-slate-500">Loading your financial records…</main>;
if(error)return <main className="min-h-screen bg-[#f6f0e5] p-6 text-center text-red-700">{error}</main>;
return <main className="min-h-screen bg-[#f6f0e5] p-4 sm:p-6"><div className="mx-auto max-w-6xl"><header className="mb-5"><p className="text-xs font-black uppercase tracking-[.18em] text-slate-500">My Finance</p><h1 className="text-2xl font-black text-slate-950">Fees & Payments</h1><p className="text-sm text-slate-500">Only your own financial records are available here.</p></header>
<div className="grid gap-4 sm:grid-cols-3"><div className="rounded-3xl bg-white p-5 border border-slate-200"><p className="text-sm text-slate-500">Outstanding</p><p className="mt-2 text-2xl font-black">{money(d.o.outstanding)}</p></div><div className="rounded-3xl bg-white p-5 border border-slate-200"><p className="text-sm text-slate-500">Overdue</p><p className="mt-2 text-2xl font-black">{money(d.o.overdue)}</p></div><div className="rounded-3xl bg-white p-5 border border-slate-200"><p className="text-sm text-slate-500">Paid</p><p className="mt-2 text-2xl font-black">{money(d.o.collected)}</p></div></div>
<section className="mt-5 overflow-x-auto rounded-3xl bg-white border border-slate-200"><h2 className="p-5 font-black">Invoices</h2><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Invoice</th><th className="p-4">Source</th><th className="p-4">Amount</th><th className="p-4">Paid</th><th className="p-4">Outstanding</th><th className="p-4">Status</th><th className="p-4">Due</th></tr></thead><tbody className="divide-y divide-slate-100">{(d.i.items||[]).map((x:any)=><tr key={x.id}><td className="p-4 font-bold">{x.invoiceNumber||x.title}</td><td className="p-4"><span className="font-semibold">{x.sourceModule||"FEES"}</span><span className="block text-xs text-slate-500">{x.sourceType||"FEE"}</span></td><td className="p-4">{money(x.amount)}</td><td className="p-4">{money(x.paidAmount)}</td><td className="p-4">{money(Math.max(0,Number(x.amount)-Number(x.paidAmount)-Number(x.refundedAmount||0)))}</td><td className="p-4">{x.status}</td><td className="p-4">{x.dueDate?new Date(x.dueDate).toLocaleDateString():"—"}</td></tr>)}</tbody></table></section>
<section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white border border-slate-200 p-5"><h2 className="font-black">Payment history</h2><div className="mt-3 space-y-3">{(d.p||[]).map((x:any)=><div key={x.id} className="flex justify-between border-b border-slate-100 pb-3"><div><p className="font-semibold">{x.method} · {x.reference||"No reference"}</p><p className="text-xs text-slate-500">{new Date(x.paidAt).toLocaleString()}</p></div><b>{money(x.amount)}</b></div>)}</div></div><div className="rounded-3xl bg-white border border-slate-200 p-5"><h2 className="font-black">Receipts</h2><div className="mt-3 space-y-3">{(d.r||[]).map((x:any)=><div key={x.id} className="flex justify-between border-b border-slate-100 pb-3"><div><p className="font-semibold">{x.receiptNumber}</p><p className="text-xs text-slate-500">{new Date(x.issuedAt).toLocaleString()}</p></div><b>{money(x.payment?.amount)}</b></div>)}</div></div></section>
</div></main>}