"use client";
import {useEffect,useState} from "react";
import {financeCollections,financeConcessions,financeInvoices,financeOverview,financePayments,financeReceipts,financeRefunds,financeTransactions} from "@/lib/financeApi";
type View="overview"|"invoices"|"payments"|"receipts"|"dues"|"collections"|"concessions"|"refunds"|"transactions"|"reports";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(n||0));
const nav:[View,string][]=[["overview","Overview"],["invoices","Invoices"],["payments","Payments"],["receipts","Receipts"],["dues","Dues & Outstanding"],["collections","Collections"],["concessions","Concessions"],["refunds","Refunds"],["transactions","Transactions"],["reports","Reports"]];
export default function FinancePage({view}: {view:View}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let live=true;setLoading(true);setError("");const load=async()=>{try{let x:any;if(view==="overview"||view==="dues")x=await financeOverview();else if(view==="invoices")x=await financeInvoices({pageSize:100});else if(view==="payments")x=await financePayments();else if(view==="receipts")x=await financeReceipts();else if(view==="collections")x=await financeCollections();else if(view==="concessions")x=await financeConcessions();else if(view==="refunds")x=await financeRefunds();else if(view==="transactions"||view==="reports")x=await financeTransactions();if(live)setData(x)}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load financial data")}finally{if(live)setLoading(false)}};void load();return()=>{live=false}},[view]);
 const title=nav.find(x=>x[0]===view)?.[1]||"Accounts";
 return <main className="min-h-screen bg-[#f6f0e5] p-4 text-slate-950 sm:p-6"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-slate-500">ACADLYX Finance</p><h1 className="mt-1 text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-slate-500">Server-authorized financial workspace</p></div><nav className="flex max-w-full gap-2 overflow-x-auto pb-1">{nav.map(([k,label])=><a key={k} href={k==="overview"?"/accounts":`/accounts/${k}`} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-bold ${k===view?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{label}</a>)}</nav></header>
  {loading?<section className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Loading financial data…</section>:error?<section className="rounded-3xl border border-red-200 bg-white p-10 text-center"><p className="font-bold text-red-700">Financial data unavailable</p><p className="mt-2 text-sm text-slate-500">{error}</p></section>:view==="overview"?<Overview d={data}/>:view==="dues"?<Dues d={data}/>:view==="collections"?<Collections d={data}/>:<TableView view={view} data={data}/>}
 </div></main>
}
function Overview({d}:any){const cards=[["Billed",d.billed],["Collected",d.collected],["Outstanding",d.outstanding],["Overdue",d.overdue],["Today",d.todayCollection],["This month",d.monthCollection]];return <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([k,v])=><section key={k} className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-slate-500">{k}</p><p className="mt-2 text-2xl font-black">{money(v)}</p></section>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-3"><section className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Collection rate</p><p className="mt-2 text-3xl font-black">{Number(d.collectionPercentage).toFixed(1)}%</p></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Invoices</p><p className="mt-2 text-3xl font-black">{d.invoiceCount}</p></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Payments</p><p className="mt-2 text-3xl font-black">{d.paymentCount}</p></section></div></>}
function Dues({d}:any){return <div className="grid gap-4 md:grid-cols-3"><section className="rounded-3xl bg-white p-6 border border-slate-200"><p className="text-sm text-slate-500">Total outstanding</p><p className="mt-2 text-3xl font-black">{money(d.outstanding)}</p></section><section className="rounded-3xl bg-white p-6 border border-slate-200"><p className="text-sm text-slate-500">Overdue</p><p className="mt-2 text-3xl font-black">{money(d.overdue)}</p></section><section className="rounded-3xl bg-white p-6 border border-slate-200"><p className="text-sm text-slate-500">Collection percentage</p><p className="mt-2 text-3xl font-black">{Number(d.collectionPercentage).toFixed(1)}%</p></section></div>}
function Collections({d}:any){return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-black">Authorized collection scope</h2><p className="mt-1 text-sm text-slate-500">Only departments visible to the authenticated financial scope are queried.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Department</th><th className="p-4">Billed</th><th className="p-4">Collected</th><th className="p-4">Outstanding</th></tr></thead><tbody className="divide-y divide-slate-100">{d.departments.map((x:any)=><tr key={x.departmentId}><td className="p-4 font-bold">{x.name}</td><td className="p-4">{money(x.billed)}</td><td className="p-4">{money(x.collected)}</td><td className="p-4">{money(x.outstanding)}</td></tr>)}</tbody></table></div></section>}
function TableView({view,data}:any){const rows=Array.isArray(data)?data:data?.items||[];const headers=view==="invoices"?["Invoice","Student","Amount","Paid","Status","Due"]:view==="payments"?["Reference","Student","Amount","Method","Date"]:view==="receipts"?["Receipt","Invoice","Student","Amount","Date"]:view==="concessions"?["Type","Amount","Reason","Status"]:view==="refunds"?["Amount","Reason","Status","Created"]:["Type","Amount","Reference","Created"];return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{headers.map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((x:any,i:number)=><tr key={x.id||i}>{view==="invoices"?<><td className="p-4 font-bold">{x.invoiceNumber||x.title}</td><td className="p-4">{x.student?.firstName} {x.student?.lastName}</td><td className="p-4">{money(x.amount)}</td><td className="p-4">{money(x.paidAmount)}</td><td className="p-4">{x.status}</td><td className="p-4">{x.dueDate?new Date(x.dueDate).toLocaleDateString():"—"}</td></>:view==="payments"?<><td className="p-4">{x.reference||x.receiptNumber||"—"}</td><td className="p-4">{x.invoice?.student?.firstName} {x.invoice?.student?.lastName}</td><td className="p-4 font-bold">{money(x.amount)}</td><td className="p-4">{x.method}</td><td className="p-4">{new Date(x.paidAt).toLocaleString()}</td></>:view==="receipts"?<><td className="p-4 font-bold">{x.receiptNumber}</td><td className="p-4">{x.invoice?.invoiceNumber||"—"}</td><td className="p-4">{x.student?.firstName} {x.student?.lastName}</td><td className="p-4">{money(x.payment?.amount)}</td><td className="p-4">{new Date(x.issuedAt).toLocaleString()}</td></>:view==="concessions"?<><td className="p-4">{x.type}</td><td className="p-4">{money(x.amount)}</td><td className="p-4">{x.reason}</td><td className="p-4">{x.status}</td></>:view==="refunds"?<><td className="p-4">{money(x.amount)}</td><td className="p-4">{x.reason}</td><td className="p-4">{x.status}</td><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td></>:<><td className="p-4">{x.type}</td><td className="p-4">{money(x.amount)}</td><td className="p-4">{x.reference||"—"}</td><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td></>}</tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-sm text-slate-500">No financial records in your authorized scope.</p>}</div></section>}
