"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { financeInvoice } from "@/lib/financeApi";
const money=(n:any)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n||0));
export default function FinanceInvoiceDetail({id}:{id:string}){
 const [d,setD]=useState<any>(null),[e,setE]=useState("");
 useEffect(()=>{financeInvoice(id).then(setD).catch(x=>setE(x instanceof Error?x.message:"Unable to load invoice"))},[id]);
 return <DashboardShell title="ACADLYX Finance" subtitle="Invoice detail" allowedRoles={["ACCOUNTS"]}><div className="mx-auto max-w-5xl space-y-5">{e?<div className="rounded-2xl border border-red-200 bg-white p-8 text-red-700">{e}</div>:!d?<div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Loading invoice…</div>:<><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/accounts/invoices" className="text-xs font-black text-emerald-700">← Back to invoices</Link><h1 className="mt-2 text-2xl font-black">{d.invoiceNumber||d.title}</h1><p className="mt-1 text-sm text-slate-500">{d.student?.firstName} {d.student?.lastName} · {d.student?.profile?.admissionNumber||"No admission number"}</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-black">{d.status}</span></header><div className="grid gap-3 sm:grid-cols-3">{[["Total",d.amount],["Paid",d.paidAmount],["Outstanding",Math.max(0,Number(d.amount)-Number(d.paidAmount)-Number(d.refundedAmount))]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase text-slate-500">{k}</p><p className="mt-2 text-2xl font-black">{money(v)}</p></div>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Invoice breakdown</h2><div className="mt-4 divide-y divide-slate-100">{(d.items||[]).map((x:any)=><div key={x.id} className="flex justify-between gap-4 py-3"><span className="font-semibold">{x.description}</span><span className="font-black">{money(x.amount)}</span></div>)}{!(d.items||[]).length&&<p className="py-6 text-sm text-slate-500">No line items recorded.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Payment history</h2><div className="mt-4 divide-y divide-slate-100">{(d.payments||[]).map((x:any)=><div key={x.id} className="flex justify-between gap-4 py-3"><div><p className="font-bold">{x.method} · {x.reference||"No reference"}</p><p className="text-xs text-slate-500">{new Date(x.paidAt).toLocaleString()}</p></div><span className="font-black">{money(x.amount)}</span></div>)}{!(d.payments||[]).length&&<p className="py-6 text-sm text-slate-500">No payments recorded.</p>}</div></section></>}</div></DashboardShell>;
}