import {Router} from "express";
import {authenticate} from "../middleware/authenticate";
import {authorize} from "../middleware/authorize";
import {requireFeature} from "../middleware/requireFeature";
import {validateBody,validateParams,validateQuery} from "../middleware/validate";
import {authorizeAnyPermission} from "../middleware/authorize";
import * as c from "../controllers/finance.controller";
import {financeInvoiceListSchema,financeInvoiceCreateSchema,financePaymentSchema,financeRefundSchema,financeIdSchema,financeExportSchema} from "../validators/finance.validators";
const router=Router();router.use(authenticate);router.use(requireFeature("fees"));
router.get("/export",authorizeAnyPermission("fees.reports.export","fees.read"),validateQuery(financeExportSchema),c.exportFinancial);
router.get("/overview",authorizeAnyPermission("fees.read","fees.collection.read"),c.overview);
router.get("/invoices",authorizeAnyPermission("fees.read","fees.read"),validateQuery(financeInvoiceListSchema),c.invoices);
router.get("/invoices/:id",authorizeAnyPermission("fees.read","fees.read"),validateParams(financeIdSchema),c.invoice);
router.post("/invoices",authorize("fees.invoice.manage"),validateBody(financeInvoiceCreateSchema),c.createInvoice);
router.post("/invoices/:id/payments",authorize("fees.payment.record"),validateParams(financeIdSchema),validateBody(financePaymentSchema),c.payment);
router.get("/payments",authorizeAnyPermission("fees.read","fees.read"),c.payments);
router.get("/receipts",authorizeAnyPermission("fees.read","fees.read"),c.receipts);
router.get("/collections",authorizeAnyPermission("fees.read","fees.read"),c.collections);
router.get("/concessions",authorizeAnyPermission("fees.read","fees.read"),c.concessions);
router.get("/refunds",authorizeAnyPermission("fees.read","fees.read"),c.refunds);
router.post("/payments/:id/refunds",authorize("fees.refund.request"),validateParams(financeIdSchema),validateBody(financeRefundSchema),c.requestRefund);
router.post("/refunds/:id/approve",authorize("fees.refund.approve"),validateParams(financeIdSchema),c.approveRefund);
router.post("/refunds/:id/process",authorize("fees.refund.process"),validateParams(financeIdSchema),c.processRefund);
router.get("/audit",authorizeAnyPermission("fees.read","audit.read"),c.auditTrail);
router.get("/transactions",authorizeAnyPermission("fees.read","fees.read"),c.transactions);
export default router;