"use client";
import {useEffect,useState} from "react";
import {DashboardShell} from "@/components/dashboard/DashboardShell";
import {authedFetch,AuthRequiredError} from "@/lib/auth";
import {useRouter} from "next/navigation";

export default function LmsSettingsPage(){
 const router=useRouter();const [s,setS]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 useEffect(()=>{void (async()=>{try{const r=await authedFetch<any>("/lms/settings");setS(r.data)}catch(e){if(e instanceof AuthRequiredError)router.replace("/login");else setError(e instanceof Error?e.message:"Settings unavailable")}})()},[router]);
 async function save(){if(!s)return;setBusy(true);setError("");try{const r=await authedFetch<any>("/lms/settings",{method:"PATCH",body:JSON.stringify({approvalRequired:s.approvalRequired,allowStudentDiscussions:s.allowStudentDiscussions,allowParentVisibility:s.allowParentVisibility,completionThreshold:Number(s.completionThreshold),certificateEnabled:s.certificateEnabled,allowExternalLinks:s.allowExternalLinks,maxResourceSizeMb:Number(s.maxResourceSizeMb),defaultLiveProvider:s.defaultLiveProvider||undefined})});setS(r.data);setNotice("LMS policy saved.")}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}finally{setBusy(false)}}
 if(!s)return <DashboardShell title="LMS Settings" subtitle="Institution LMS governance and policies"><div className="rounded-2xl bg-white p-6">{error||"Loading…"}</div></DashboardShell>;
 return <DashboardShell title="LMS Settings" subtitle="Institution LMS governance and policies"><div className="mx-auto max-w-3xl space-y-5">{error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{notice&&<div role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-700">{notice}</div>}<section className="space-y-4 rounded-3xl border bg-white p-6">{[["approvalRequired","Require course approval before publishing"],["allowStudentDiscussions","Allow student discussions"],["allowParentVisibility","Allow linked parents to view LMS"],["certificateEnabled","Enable course completion certificates"],["allowExternalLinks","Allow external lesson links"]].map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 rounded-xl border p-4"><span className="font-bold">{label}</span><input type="checkbox" checked={Boolean(s[key])} onChange={e=>setS({...s,[key]:e.target.checked})}/></label>)}<label className="block"><span className="text-sm font-bold">Completion threshold (%)</span><input type="number" min="1" max="100" value={s.completionThreshold} onChange={e=>setS({...s,completionThreshold:e.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block"><span className="text-sm font-bold">Maximum resource size (MB)</span><input type="number" min="1" max="500" value={s.maxResourceSizeMb} onChange={e=>setS({...s,maxResourceSizeMb:e.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="block"><span className="text-sm font-bold">Default live-class provider</span><input value={s.defaultLiveProvider||""} onChange={e=>setS({...s,defaultLiveProvider:e.target.value})} placeholder="Zoom, Google Meet, Teams…" className="mt-2 w-full rounded-xl border p-3"/></label><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?"Saving…":"Save LMS policies"}</button></section></div></DashboardShell>
}
