"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { authedFetch } from "@/lib/auth";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5001/api/v1";
export default function SiteContentPage(){ const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 useEffect(()=>{authedFetch<any>("/site-content").then(r=>setData(r.data)).catch(e=>setMsg(e.message))},[]);
 function set(path:string,value:any){setData((old:any)=>{const next=structuredClone(old);let cur=next;const parts=path.split(".");for(let i=0;i<parts.length-1;i++)cur=cur[parts[i]];cur[parts.at(-1)!]=value;return next})}
 async function save(){setBusy(true);setMsg("");try{await authedFetch("/site-content",{method:"PUT",body:JSON.stringify(data)});setMsg("Website content saved and published.")}catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 async function upload(e:ChangeEvent<HTMLInputElement>,path:string){const f=e.target.files?.[0];if(!f)return;setBusy(true);try{const fd=new FormData();fd.append("file",f);const r=await fetch(`${api}/site-content/media`,{method:"POST",headers:{Authorization:`Bearer ${localStorage.getItem("acadlyx_access_token")||""}`},body:fd});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||"Upload failed");set(path,b.data.url);setMsg("Image uploaded. Save to publish it.")}catch(e){setMsg(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
 if(!data)return <DashboardShell title="Website CMS"><div className="rounded-2xl bg-white p-6">{msg||"Loading website content…"}</div></DashboardShell>;
 return <DashboardShell title="Website CMS" subtitle="Control public website content without editing code" allowedRoles={["INSTITUTION_ADMIN","DIRECTOR","MANAGEMENT"]}><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Public website control center</p><h1 className="mt-2 text-2xl font-bold">100% Dynamic Content</h1><p className="mt-1 text-sm text-slate-500">Text, logos, hero images, features, statistics, gallery, contact and footer.</p></div><button onClick={save} disabled={busy} className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save & publish"}</button></div>{msg&&<div className="mb-5 rounded-xl bg-slate-100 p-3 text-sm">{msg}</div>}
 <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Branding</h2><div className="mt-4 space-y-4"><Field label="Site name" value={data.brand.siteName} onChange={v=>set("brand.siteName",v)}/><Field label="Tagline" value={data.brand.tagline} onChange={v=>set("brand.tagline",v)}/><ImageField label="ACADLYX logo" value={data.brand.acadlyxLogoUrl} onChange={v=>set("brand.acadlyxLogoUrl",v)} upload={e=>upload(e,"brand.acadlyxLogoUrl")}/><ImageField label="AIMT / institution logo" value={data.brand.institutionLogoUrl} onChange={v=>set("brand.institutionLogoUrl",v)} upload={e=>upload(e,"brand.institutionLogoUrl")}/></div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Hero</h2><div className="mt-4 space-y-4"><Field label="Eyebrow" value={data.hero.eyebrow} onChange={v=>set("hero.eyebrow",v)}/><Field label="Title" value={data.hero.title} onChange={v=>set("hero.title",v)}/><TextArea label="Description" value={data.hero.description} onChange={v=>set("hero.description",v)}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Primary CTA label" value={data.hero.primaryCtaLabel} onChange={v=>set("hero.primaryCtaLabel",v)}/><Field label="Primary CTA URL" value={data.hero.primaryCtaHref} onChange={v=>set("hero.primaryCtaHref",v)}/><Field label="Secondary CTA label" value={data.hero.secondaryCtaLabel} onChange={v=>set("hero.secondaryCtaLabel",v)}/><Field label="Secondary CTA URL" value={data.hero.secondaryCtaHref} onChange={v=>set("hero.secondaryCtaHref",v)}/></div></div></section>
 <section className="rounded-2xl border bg-white p-5 xl:col-span-2"><h2 className="font-semibold">Features</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{data.sections.features.map((f:any,i:number)=><div key={i} className="rounded-xl bg-slate-50 p-4"><Field label={`Title ${i+1}`} value={f.title} onChange={v=>{const x=[...data.sections.features];x[i]={...x[i],title:v};set("sections.features",x)}}/><TextArea label="Text" value={f.text} onChange={v=>{const x=[...data.sections.features];x[i]={...x[i],text:v};set("sections.features",x)}}/></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Institution stats</h2><div className="mt-4 space-y-3">{data.sections.stats.map((s:any,i:number)=><div key={i} className="grid grid-cols-2 gap-2"><Field label="Label" value={s.label} onChange={v=>{const x=[...data.sections.stats];x[i]={...x[i],label:v};set("sections.stats",x)}}/><Field label="Value" value={s.value} onChange={v=>{const x=[...data.sections.stats];x[i]={...x[i],value:v};set("sections.stats",x)}}/></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Contact & footer</h2><div className="mt-4 space-y-3"><Field label="Email" value={data.contact.email} onChange={v=>set("contact.email",v)}/><Field label="Phone" value={data.contact.phone} onChange={v=>set("contact.phone",v)}/><Field label="Address" value={data.contact.address} onChange={v=>set("contact.address",v)}/><Field label="Website" value={data.contact.website} onChange={v=>set("contact.website",v)}/><Field label="Footer text" value={data.footer.text} onChange={v=>set("footer.text",v)}/></div></section></div></div></DashboardShell> }
function Field({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-semibold text-slate-500">{label}</span><input value={value??""} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-slate-500"/></label>}
function TextArea({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-semibold text-slate-500">{label}</span><textarea value={value??""} onChange={e=>onChange(e.target.value)} rows={3} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-slate-500"/></label>}
function ImageField({label,value,onChange,upload}:{label:string;value:any;onChange:(v:string)=>void;upload:(e:ChangeEvent<HTMLInputElement>)=>void}){return <div><Field label={label+" URL"} value={value} onChange={onChange}/><input type="file" accept="image/*" onChange={upload} className="mt-2 block w-full text-xs"/>{value&&<img src={value} alt="Preview" className="mt-2 h-16 w-16 rounded-lg border object-contain"/>}</div>}


