"use client";

import { FormEvent, useEffect, useState } from "react";
import { authedFetch, AuthRequiredError, clearTokens } from "@/lib/auth";
import { useRouter } from "next/navigation";

type Account = { email: string; firstName: string; lastName: string; phone: string | null; institution: { name: string; logoUrl: string | null } | null; lastLoginAt: string | null };

export function AccountMenu() {
  const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(false); const [password, setPassword] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { authedFetch<{ success: true; data: Account }>("/auth/account").then(r => setAccount(r.data)).catch(e => { if (!(e instanceof AuthRequiredError)) setAccount(null); }); }, []);
  if (!account) return null;
  async function saveProfile(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); try { const r = await authedFetch<{success:true;data:Account}>("/auth/account", { method:"PATCH", body: JSON.stringify({ firstName: form.get("firstName"), lastName: form.get("lastName"), phone: form.get("phone") || null }) }); setAccount({ ...account, ...r.data }); setEditing(false); setMessage("Profile saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save profile."); } }
  async function savePassword(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form=new FormData(e.currentTarget); if(form.get("newPassword")!==form.get("confirmPassword")){setMessage("New passwords do not match.");return;} try { await authedFetch("/auth/change-password", {method:"POST",body:JSON.stringify({currentPassword:form.get("currentPassword"),newPassword:form.get("newPassword")})}); clearTokens(); router.replace("/login"); } catch(e){setMessage(e instanceof Error?e.message:"Unable to change password.");} }
  return <><button onClick={() => {setOpen(true);setMessage("")}} className="fixed bottom-5 right-5 z-50 rounded-full bg-slate-950 px-4 py-3 text-xs font-semibold text-white shadow-xl shadow-slate-950/25 transition hover:-translate-y-0.5">Account</button>{open && <div className="fixed inset-0 z-[60] flex items-end justify-center bg-slate-950/45 p-4 sm:items-center"><section className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">My account</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{account.firstName} {account.lastName}</h2><p className="text-sm text-slate-500">{account.institution?.name || "ACADLYX Platform"}</p></div><button onClick={()=>setOpen(false)} className="rounded-lg px-3 py-2 text-sm text-slate-500 hover:bg-slate-100">Close</button></div>{message&&<p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm text-slate-700">{message}</p>}<div className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-medium text-slate-900">{account.email}</p><p className="mt-1 text-slate-500">Last sign-in: {account.lastLoginAt ? new Date(account.lastLoginAt).toLocaleString() : "Not available"}</p></div><div className="mt-5 flex gap-2"><button onClick={()=>{setEditing(!editing);setPassword(false)}} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold">Edit profile</button><button onClick={()=>{setPassword(!password);setEditing(false)}} className="rounded-xl bg-slate-950 px-3 py-2 text-sm font-semibold text-white">Change password</button></div>{editing&&<form onSubmit={saveProfile} className="mt-5 grid gap-3"><input name="firstName" defaultValue={account.firstName} required className="rounded-xl border p-3 text-sm"/><input name="lastName" defaultValue={account.lastName} required className="rounded-xl border p-3 text-sm"/><input name="phone" defaultValue={account.phone||""} placeholder="Phone" className="rounded-xl border p-3 text-sm"/><button className="rounded-xl bg-cyan-500 px-4 py-3 text-sm font-bold text-slate-950">Save profile</button></form>}{password&&<form onSubmit={savePassword} className="mt-5 grid gap-3"><input name="currentPassword" type="password" required placeholder="Current password" className="rounded-xl border p-3 text-sm"/><input name="newPassword" type="password" minLength={10} required placeholder="New password (10+ characters)" className="rounded-xl border p-3 text-sm"/><input name="confirmPassword" type="password" minLength={10} required placeholder="Confirm new password" className="rounded-xl border p-3 text-sm"/><button className="rounded-xl bg-cyan-500 px-4 py-3 text-sm font-bold text-slate-950">Change and sign out</button></form>}</section></div>}</>;
}
