"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { AuthRequiredError } from "@/lib/auth";
import { getMyFacultyDashboard } from "@/lib/facultyApi";
import { getParentDashboard } from "@/lib/portalApi";

function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}<button onClick={retry} className="ml-3 font-semibold underline">Retry</button></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-slate-100 py-3 text-sm last:border-0"><span className="text-slate-500">{label}</span><span className="text-right font-medium text-slate-800">{value || "—"}</span></div>; }

export function FacultyProfilePage() {
  const router = useRouter(); const [data, setData] = useState<Awaited<ReturnType<typeof getMyFacultyDashboard>> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); setError(""); getMyFacultyDashboard().then(setData).catch((reason: Error) => { if (reason instanceof AuthRequiredError) router.replace("/login"); else setError(reason.message || "Unable to load faculty profile."); }).finally(() => setLoading(false)); }, [router]);
  useEffect(() => { load(); }, [load]);
  return <DashboardShell title="My Profile" subtitle="Teaching identity and assigned academic responsibilities" allowedRoles={["FACULTY"]}><main className="mx-auto max-w-5xl space-y-4">{loading && <div className="h-56 animate-pulse rounded-lg bg-slate-200" />}{error && <ErrorState message={error} retry={load} />}{data && !loading && <><section className="rounded-lg border border-slate-200 bg-white p-6"><h1 className="text-xl font-semibold">{data.faculty.firstName} {data.faculty.lastName}</h1><p className="mt-1 text-sm text-slate-500">{data.faculty.email}</p></section><section className="grid gap-4 md:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Academic responsibilities</h2><Row label="Assigned course offerings" value={String(data.assignedCourseOfferings.length)} /><Row label="Classes today" value={String(data.todaysClassCount)} /><Row label="Open attendance sessions" value={String(data.pending.attendanceSessions)} /><Row label="Submissions to review" value={String(data.pending.assignmentsToReview)} /></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Assigned courses</h2>{data.assignedCourseOfferings.length ? <ul className="mt-3 space-y-2">{data.assignedCourseOfferings.map((offering) => <li key={offering.id} className="rounded-md bg-slate-50 p-3 text-sm"><span className="font-medium">{offering.course.code} · {offering.course.name}</span><span className="mt-1 block text-slate-500">{offering.semester.program.name} · {offering.section.name}</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No course offerings are currently assigned.</p>}</section></section></>}</main></DashboardShell>;
}

export function ParentProfilePage() {
  const router = useRouter(); const [data, setData] = useState<Awaited<ReturnType<typeof getParentDashboard>> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); setError(""); getParentDashboard().then(setData).catch((reason: Error) => { if (reason instanceof AuthRequiredError) router.replace("/login"); else setError(reason.message || "Unable to load parent profile."); }).finally(() => setLoading(false)); }, [router]);
  useEffect(() => { load(); }, [load]);
  return <DashboardShell title="My Profile" subtitle="Parent account and linked learner records" allowedRoles={["PARENT"]}><main className="mx-auto max-w-5xl space-y-4">{loading && <div className="h-56 animate-pulse rounded-lg bg-slate-200" />}{error && <ErrorState message={error} retry={load} />}{data && !loading && <><section className="rounded-lg border border-slate-200 bg-white p-6"><h1 className="text-xl font-semibold">{data.parent.firstName} {data.parent.lastName}</h1><p className="mt-1 text-sm text-slate-500">{data.parent.email}{data.parent.phone ? ` · ${data.parent.phone}` : ""}</p></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Linked students</h2>{data.children.length ? <div className="mt-3 divide-y divide-slate-100">{data.children.map((child) => <article key={child.student.id} className="py-3"><p className="font-medium">{child.student.firstName} {child.student.lastName}</p><p className="text-sm text-slate-500">{child.enrollment?.program.name || "Program not assigned"} · {child.enrollment?.section?.name || "Section not assigned"}</p><p className="mt-1 text-sm text-slate-600">Attendance {child.attendance.percentage}% · Outstanding fees ₹{child.fees.reduce((sum, fee) => sum + fee.balance, 0).toLocaleString("en-IN")}</p></article>)}</div> : <p className="mt-3 text-sm text-slate-500">No students are linked to this parent account.</p>}</section></>}</main></DashboardShell>;
}
