CREATE TABLE "department_accesses" ("userId" TEXT NOT NULL, "departmentId" TEXT NOT NULL, "scope" TEXT NOT NULL DEFAULT 'HOD', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "department_accesses_pkey" PRIMARY KEY ("userId","departmentId"));
CREATE TABLE "skills" ("id" TEXT NOT NULL, "institutionId" TEXT NOT NULL, "name" TEXT NOT NULL, "category" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "skills_pkey" PRIMARY KEY ("id"));
CREATE TABLE "target_roles" ("id" TEXT NOT NULL, "institutionId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "target_roles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "role_skills" ("targetRoleId" TEXT NOT NULL, "skillId" TEXT NOT NULL, "weight" INTEGER NOT NULL DEFAULT 1, "minimumLevel" INTEGER NOT NULL DEFAULT 60, CONSTRAINT "role_skills_pkey" PRIMARY KEY ("targetRoleId","skillId"));
CREATE TABLE "student_skills" ("studentId" TEXT NOT NULL, "skillId" TEXT NOT NULL, "institutionId" TEXT NOT NULL, "proficiency" INTEGER NOT NULL DEFAULT 0, "evidence" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "student_skills_pkey" PRIMARY KEY ("studentId","skillId"));
CREATE TABLE "career_paths" ("id" TEXT NOT NULL, "studentId" TEXT NOT NULL, "targetRoleId" TEXT NOT NULL, "isPrimary" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "career_paths_pkey" PRIMARY KEY ("id"));
CREATE TABLE "opportunities" ("id" TEXT NOT NULL, "institutionId" TEXT NOT NULL, "targetRoleId" TEXT, "title" TEXT NOT NULL, "organization" TEXT NOT NULL, "description" TEXT, "deadline" TIMESTAMP(3), "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "opportunities_pkey" PRIMARY KEY ("id"));
CREATE TABLE "applications" ("id" TEXT NOT NULL, "institutionId" TEXT NOT NULL, "studentId" TEXT NOT NULL, "opportunityId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'APPLIED', "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "applications_pkey" PRIMARY KEY ("id"));
CREATE INDEX "department_accesses_departmentId_idx" ON "department_accesses"("departmentId");
CREATE INDEX "skills_institutionId_idx" ON "skills"("institutionId");
CREATE UNIQUE INDEX "skills_institutionId_name_key" ON "skills"("institutionId", "name");
CREATE INDEX "target_roles_institutionId_idx" ON "target_roles"("institutionId");
CREATE UNIQUE INDEX "target_roles_institutionId_name_key" ON "target_roles"("institutionId", "name");
CREATE INDEX "role_skills_skillId_idx" ON "role_skills"("skillId");
CREATE INDEX "student_skills_institutionId_idx" ON "student_skills"("institutionId");
CREATE INDEX "student_skills_skillId_idx" ON "student_skills"("skillId");
CREATE INDEX "career_paths_targetRoleId_idx" ON "career_paths"("targetRoleId");
CREATE UNIQUE INDEX "career_paths_studentId_targetRoleId_key" ON "career_paths"("studentId", "targetRoleId");
CREATE INDEX "opportunities_institutionId_idx" ON "opportunities"("institutionId");
CREATE INDEX "opportunities_targetRoleId_idx" ON "opportunities"("targetRoleId");
CREATE UNIQUE INDEX "applications_studentId_opportunityId_key" ON "applications"("studentId", "opportunityId");
CREATE INDEX "applications_institutionId_idx" ON "applications"("institutionId");
CREATE INDEX "applications_opportunityId_idx" ON "applications"("opportunityId");
ALTER TABLE "department_accesses" ADD CONSTRAINT "department_accesses_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "department_accesses" ADD CONSTRAINT "department_accesses_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "skills" ADD CONSTRAINT "skills_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "target_roles" ADD CONSTRAINT "target_roles_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_skills" ADD CONSTRAINT "role_skills_targetRoleId_fkey" FOREIGN KEY ("targetRoleId") REFERENCES "target_roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_skills" ADD CONSTRAINT "role_skills_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "student_skills" ADD CONSTRAINT "student_skills_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "student_skills" ADD CONSTRAINT "student_skills_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "student_skills" ADD CONSTRAINT "student_skills_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "career_paths" ADD CONSTRAINT "career_paths_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "career_paths" ADD CONSTRAINT "career_paths_targetRoleId_fkey" FOREIGN KEY ("targetRoleId") REFERENCES "target_roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_targetRoleId_fkey" FOREIGN KEY ("targetRoleId") REFERENCES "target_roles"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "institutions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "applications" ADD CONSTRAINT "applications_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE CASCADE;
